import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import {CalendarDays,Clock3,Users,ClipboardList,Settings,LogOut,Plus,Trash2,Edit3,ChevronLeft,ChevronRight,Shield,MapPin,Bell,Search,X,UserPlus} from 'lucide-react';
import './styles.css';

const URL=import.meta.env.VITE_SUPABASE_URL;
const KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const supabase=(URL&&KEY)?createClient(URL,KEY):null;
const MIN_DATE='2026-09-27', MAX_DATE='2026-10-31';
const fmt=d=>new Intl.DateTimeFormat('th-TH',{day:'numeric',month:'short',year:'numeric'}).format(new Date(d+'T00:00:00'));
const todayISO=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const clampDate=d=>d<MIN_DATE?MIN_DATE:d>MAX_DATE?MAX_DATE:d;
const timeToMin=t=>{const [h,m]=String(t).slice(0,5).split(':').map(Number);return h*60+m};
const overlap=(a,b)=>timeToMin(a.start_time||a.start)<timeToMin(b.end_time||b.end)&&timeToMin(b.start_time||b.start)<timeToMin(a.end_time||a.end);

async function loadData(){
 const [p,a,s,j,jm]=await Promise.all([
  supabase.from('profiles').select('id,email,display_name,role,created_at').order('display_name'),
  supabase.from('availability').select('id,user_id,date,start_time,end_time').order('date').order('start_time'),
  supabase.from('day_status').select('user_id,date,status'),
  supabase.from('jobs').select('id,title,date,start_time,end_time,location,notes,created_by,created_at').order('date').order('start_time'),
  supabase.from('job_members').select('job_id,user_id')
 ]);
 for(const r of [p,a,s,j,jm]) if(r.error) throw r.error;
 const members={};
 jm.data.forEach(x=>(members[x.job_id]??=[]).push(x.user_id));
 return {users:p.data||[],avail:a.data||[],dayStatus:s.data||[],jobs:(j.data||[]).map(x=>({...x,members:members[x.id]||[]}))};
}

function App(){
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[data,setData]=useState({users:[],avail:[],dayStatus:[],jobs:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[authMode,setAuthMode]=useState('login');
 const refresh=async()=>{try{setError('');const d=await loadData();setData(d);const me=d.users.find(x=>x.id===session?.user?.id);setProfile(me||null)}catch(e){setError(e.message||'โหลดข้อมูลไม่สำเร็จ')}};
 useEffect(()=>{if(!supabase){setError('ยังไม่ได้ตั้งค่า Supabase');setLoading(false);return} supabase.auth.getSession().then(async({data})=>{setSession(data.session);if(data.session){try{const d=await loadData();setData(d);setProfile(d.users.find(x=>x.id===data.session.user.id)||null)}catch(e){setError(e.message||'โหลดข้อมูลไม่สำเร็จ')}}setLoading(false)});const {data:listener}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(s);if(!s){setProfile(null);setData({users:[],avail:[],dayStatus:[],jobs:[]})}});return()=>listener.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session&&!profile) refresh()},[session]);
 if(loading)return <div className="auth"><div className="auth-card"><div className="brand">chownatui<span>.</span></div><p className="tag">กำลังเชื่อมต่อระบบ...</p></div></div>;
 if(!session||!profile)return <Auth mode={authMode} setMode={setAuthMode} error={error} setError={setError}/>;
 return <Dashboard me={profile} data={data} refresh={refresh} error={error} logout={async()=>{await supabase.auth.signOut();setSession(null)}}/>;
}

function Auth({mode,setMode,error,setError}){const [email,setEmail]=useState(''),[pw,setPw]=useState(''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 async function submit(e){e.preventDefault();setError('');setMsg('');if(!supabase)return;setBusy(true);try{if(mode==='login'){const {error}=await supabase.auth.signInWithPassword({email,password:pw});if(error)throw error}else{if(!name.trim())throw new Error('กรุณาใส่ชื่อที่จะแสดง');const {data,error}=await supabase.auth.signUp({email,password:pw,options:{data:{display_name:name.trim()}}});if(error)throw error;if(data.session) setMsg('สมัครสำเร็จ กำลังเข้าสู่ระบบ...');else setMsg('สมัครสำเร็จ กรุณาตรวจอีเมลเพื่อยืนยันบัญชีก่อนเข้าสู่ระบบ')}}catch(e){setError(e.message||'เกิดข้อผิดพลาด')}finally{setBusy(false)}}
 return <div className="auth"><div className="auth-card"><div className="brand">chownatui<span>.</span></div><p className="tag">จัดการเวลาของทีมให้ง่ายกว่าเดิม</p><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>{setMode('login');setError('')}}>เข้าสู่ระบบ</button><button className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('')}}>สมัครสมาชิก</button></div><form onSubmit={submit}>{mode==='signup'&&<label>ชื่อที่จะแสดง<input value={name} onChange={e=>setName(e.target.value)} placeholder="เช่น กอตอ" required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="อย่างน้อย 6 ตัวอักษร" minLength={6} required/></label>{(error||msg)&&<div className={error?'error':'notice'}>{error||msg}</div>}<button className="primary wide" disabled={busy}>{busy?'กำลังดำเนินการ...':mode==='login'?'เข้าสู่ระบบ':'สร้างบัญชี'}</button></form><small>บัญชีใหม่จะเริ่มต้นเป็น Member และ Admin สามารถเปลี่ยนสิทธิ์ภายหลัง</small></div></div>}

function Dashboard({me,data,refresh,error,logout}){const [page,setPage]=useState('home'),[date,setDate]=useState(clampDate(todayISO()));const nav=[['home','หน้าหลัก',CalendarDays],['availability','ลงเวลา',Clock3],['team','ภาพรวม',Users],['jobs','งาน',ClipboardList],...(me.role==='admin'?[['admin','จัดการตุ้ย',Settings]]:[])];return <div className="app"><aside><div className="brand side">chownatui<span>.</span></div>{nav.map(([id,t,I])=><button className={page===id?'nav active':'nav'} key={id} onClick={()=>setPage(id)}><I size={19}/>{t}</button>)}<div className="side-bottom"><div className="me"><div className="avatar">{me.display_name?.[0]||'U'}</div><div><b>{me.display_name}</b><small>{me.role==='admin'?'👑 Admin':'Member'}</small></div></div><button className="nav" onClick={logout}><LogOut size={18}/>ออกจากระบบ</button></div></aside><main><header><div><div className="mobile-brand">chownatui<span>.</span></div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1></div><div className="header-user"><Bell size={19}/><span>{me.display_name}</span></div></header>{error&&<div className="error global-error">⚠️ {error}<button onClick={refresh}>ลองใหม่</button></div>}{page==='home'&&<Home me={me} data={data} date={date} setDate={setDate} go={setPage}/>} {page==='availability'&&<Availability me={me} data={data} date={date} setDate={setDate} refresh={refresh}/>} {page==='team'&&<Team data={data} date={date} setDate={setDate}/>} {page==='jobs'&&<Jobs me={me} data={data} date={date} setDate={setDate} refresh={refresh}/>} {page==='admin'&&me.role==='admin'&&<Admin data={data} refresh={refresh} me={me}/>}</main><nav className="bottom-nav">{nav.slice(0,4).map(([id,t,I])=><button className={page===id?'active':''} key={id} onClick={()=>setPage(id)}><I size={20}/><span>{t}</span></button>)}{me.role==='admin'&&<button className={page==='admin'?'active':''} onClick={()=>setPage('admin')}><Settings size={20}/><span>จัดการ</span></button>}</nav></div>}

function DatePicker({date,setDate}){const shift=n=>{const d=new Date(date+'T00:00:00');d.setDate(d.getDate()+n);setDate(clampDate(d.toISOString().slice(0,10)))};return <div className="datebar"><button onClick={()=>shift(-1)} disabled={date===MIN_DATE}><ChevronLeft/></button><div><CalendarDays size={18}/><b>{fmt(date)}</b></div><button onClick={()=>shift(1)} disabled={date===MAX_DATE}><ChevronRight/></button></div>}
function Home({me,data,date,setDate,go}){const av=data.avail.filter(a=>a.user_id===me.id&&a.date===date),js=data.jobs.filter(j=>j.date===date&&j.members.includes(me.id)),status=data.dayStatus.find(x=>x.user_id===me.id&&x.date===date)?.status;return <section><div className="hero"><div><span className="eyebrow">วันนี้มีอะไรบ้าง?</span><h2>สวัสดี {me.display_name} 👋</h2><p>จัดการเวลาของคุณและดูงานของทีมได้จากที่เดียว</p></div><DatePicker date={date} setDate={setDate}/></div><div className="grid2"><div className="card"><div className="card-title"><span>{status==='available'?'🟢 ว่าง':status==='unavailable'?'🔴 ไม่ว่าง':'⚪ ยังไม่ลงเวลา'}</span><button className="link" onClick={()=>go('availability')}>จัดการ</button></div>{status==='available'&&av.length?<div className="chips">{av.map(a=><span key={a.id} className="chip green">{a.start_time.slice(0,5)}–{a.end_time.slice(0,5)}</span>)}</div>:<p className="muted">{status==='unavailable'?'วันนี้คุณเลือกไม่ว่าง':status==='available'?'ยังไม่ได้เพิ่มช่วงเวลาว่าง':'วันนี้ยังไม่ได้ลงเวลา'}</p>}</div><div className="card"><div className="card-title"><span>🔒 งานของฉัน</span><button className="link" onClick={()=>go('jobs')}>ดูงาน</button></div>{js.length?js.map(j=><div className="mini-job" key={j.id}><b>{j.title}</b><span>{j.start_time.slice(0,5)}–{j.end_time.slice(0,5)}</span></div>):<p className="muted">วันนี้ยังไม่มีงาน</p>}</div></div><div className="quick"><button onClick={()=>go('availability')}><Clock3/><b>ลงเวลาว่าง</b><small>เลือกสถานะและช่วงเวลา</small></button><button onClick={()=>go('team')}><Users/><b>ดูภาพรวม</b><small>เช็กว่าใครว่าง</small></button><button onClick={()=>go('jobs')}><ClipboardList/><b>ดูงาน</b><small>งานที่ได้รับมอบหมาย</small></button></div></section>}

function Availability({me,data,date,setDate,refresh}){const [open,setOpen]=useState(false),[edit,setEdit]=useState(null),[start,setStart]=useState('09:00'),[end,setEnd]=useState('12:00'),[err,setErr]=useState('');const items=data.avail.filter(a=>a.user_id===me.id&&a.date===date).sort((a,b)=>a.start_time.localeCompare(b.start_time)),jobs=data.jobs.filter(j=>j.date===date&&j.members.includes(me.id)),status=data.dayStatus.find(x=>x.user_id===me.id&&x.date===date)?.status||null;
 async function setStatus(next){setErr('');const {error}=await supabase.from('day_status').upsert({user_id:me.id,date,status:next},{onConflict:'user_id,date'});if(error)return setErr(error.message);if(next==='unavailable'){const r=await supabase.from('availability').delete().eq('user_id',me.id).eq('date',date);if(r.error)return setErr(r.error.message)}await refresh()}
 async function save(){setErr('');if(status!=='available')return setErr('กรุณาเลือกสถานะ “ว่าง” ก่อนลงช่วงเวลา');if(timeToMin(start)>=timeToMin(end))return setErr('เวลาไม่ถูกต้อง');const x={user_id:me.id,date,start_time:start,end_time:end};if(jobs.some(j=>overlap(x,j)))return setErr('ช่วงเวลานี้มีงานอยู่แล้ว');if(items.some(a=>a.id!==edit?.id&&overlap(x,a)))return setErr('ช่วงเวลานี้ซ้อนกับเวลาว่างเดิม');const r=edit?await supabase.from('availability').update({start_time:start,end_time:end}).eq('id',edit.id):await supabase.from('availability').insert(x);if(r.error)return setErr(r.error.message);setOpen(false);setEdit(null);await refresh()}
 async function remove(id){if(!confirm('ลบช่วงเวลานี้ใช่ไหม?'))return;const {error}=await supabase.from('availability').delete().eq('id',id);if(error)setErr(error.message);else await refresh()}
 return <section><div className="section-top"><div><h2>ลงเวลาตุ้ย</h2><p>เลือกสถานะของวันนี้ก่อน แล้วจึงลงช่วงเวลาว่าง</p></div><div className="status-toggle"><button className={status==='available'?'selected green-btn':''} onClick={()=>setStatus('available')}>🟢 ว่าง</button><button className={status==='unavailable'?'selected red-btn':''} onClick={()=>setStatus('unavailable')}>🔴 ไม่ว่าง</button></div></div><DatePicker date={date} setDate={setDate}/>{err&&<div className="error">⚠️ {err}</div>}{!status&&<div className="notice">⚪ วันนี้ยังไม่ได้ลงสถานะ — เลือก “ว่าง” หรือ “ไม่ว่าง” ก่อน</div>}{status==='unavailable'&&<div className="unavailable-box">🔴 <b>วันนี้ไม่ว่าง</b><span>คุณเลือกสถานะไม่ว่างเอง จึงไม่สามารถเพิ่มช่วงเวลาว่างของวันนี้ได้</span></div>}{status==='available'&&<button className="primary" onClick={()=>{setEdit(null);setStart('09:00');setEnd('12:00');setOpen(true)}}><Plus size={18}/>เพิ่มเวลาว่าง</button>}<div className="timeline">{jobs.map(j=><div className="time-card locked" key={j.id}><div className="time"><b>{j.start_time.slice(0,5)}–{j.end_time.slice(0,5)}</b><span>🔒 มีงานนะ</span></div><div><b>{j.title}</b><small>{j.location||'ไม่ระบุสถานที่'}</small></div></div>)}{status==='available'&&items.map(a=><div className="time-card free" key={a.id}><div className="time"><b>{a.start_time.slice(0,5)}–{a.end_time.slice(0,5)}</b><span>🟢 ว่าง</span></div><div className="actions"><button onClick={()=>{setEdit(a);setStart(a.start_time.slice(0,5));setEnd(a.end_time.slice(0,5));setOpen(true)}}><Edit3 size={17}/></button><button onClick={()=>remove(a.id)}><Trash2 size={17}/></button></div></div>)}{status==='available'&&!items.length&&!jobs.length&&<div className="empty">เลือก “ว่าง” แล้วเพิ่มช่วงเวลาที่สะดวกได้เลย</div>}{status==='unavailable'&&!jobs.length&&<div className="empty">ไม่มีงานในวันนี้</div>}</div>{open&&<Modal title={edit?'แก้ไขเวลาว่าง':'เพิ่มเวลาว่าง'} close={()=>setOpen(false)}><label>เริ่ม<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>ถึง<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label>{err&&<div className="error">⚠️ {err}</div>}<button className="primary wide" onClick={save}>บันทึก</button></Modal>}</section>}

function Team({data,date,setDate}){const [q,setQ]=useState('');const users=data.users.filter(u=>u.display_name.toLowerCase().includes(q.toLowerCase()));return <section><div className="section-top"><div><h2>ภาพรวมตุ้ย</h2><p>ดูสถานะและเวลาของทุกคนในทีม</p></div><div className="search"><Search size={17}/><input placeholder="ค้นหาสมาชิก" value={q} onChange={e=>setQ(e.target.value)}/></div></div><DatePicker date={date} setDate={setDate}/><div className="member-grid">{users.map(u=>{const av=data.avail.filter(a=>a.user_id===u.id&&a.date===date),js=data.jobs.filter(j=>j.date===date&&j.members.includes(u.id)),status=data.dayStatus.find(x=>x.user_id===u.id&&x.date===date)?.status||null;const label=!status?'⚪ ยังไม่ลงเวลา':status==='unavailable'?'🔴 ไม่ว่าง':js.length?'🟡 มีงานนะ':'🟢 ว่าง';const cls=!status?'status gray':status==='unavailable'?'status red':js.length?'status yellow':'status green';return <div className="member-card" key={u.id}><div className="member-head"><div className="avatar big">{u.display_name[0]}</div><div><h3>{u.display_name}</h3><small>{u.role==='admin'?'👑 Admin':'Member'}</small></div><span className={cls}>{label}</span></div>{js.map(j=><div className="line locked" key={j.id}><span>🔒 {j.start_time.slice(0,5)}–{j.end_time.slice(0,5)}</span><b>{j.title}</b></div>)}{status==='available'&&av.map(a=><div className="line" key={a.id}><span>🟢 {a.start_time.slice(0,5)}–{a.end_time.slice(0,5)}</span></div>)}{!av.length&&!js.length&&<div className="muted">{status==='unavailable'?'วันนี้ไม่ว่าง':!status?'ยังไม่ได้ลงเวลา':'ยังไม่มีช่วงเวลาว่าง'}</div>}</div>})}</div></section>}

function Jobs({me,data,date,setDate,refresh}){const isAdmin=me.role==='admin';const [open,setOpen]=useState(false),[edit,setEdit]=useState(null);const jobs=data.jobs.filter(j=>j.date===date&&(isAdmin||j.members.includes(me.id)));return <section><div className="section-top"><div><h2>งานตุ้ย</h2><p>{isAdmin?'สร้างและจัดการงานของทีม':'งานที่ได้รับมอบหมายให้คุณ'}</p></div>{isAdmin&&<button className="primary" onClick={()=>{setEdit(null);setOpen(true)}}><Plus size={18}/>สร้างงาน</button>}</div><DatePicker date={date} setDate={setDate}/><div className="job-list">{jobs.map(j=><JobCard key={j.id} job={j} data={data} admin={isAdmin} onEdit={()=>{setEdit(j);setOpen(true)}}/>)}{!jobs.length&&<div className="empty">ยังไม่มีงานในวันที่เลือก</div>}</div>{open&&<JobModal job={edit} data={data} date={date} me={me} close={()=>setOpen(false)} refresh={refresh}/>}</section>}
function JobCard({job,data,admin,onEdit}){return <div className="job-card"><div className="job-icon">🎥</div><div className="job-main"><div className="job-title"><h3>{job.title}</h3>{admin&&<button onClick={onEdit}><Edit3 size={16}/></button>}</div><div className="job-meta"><span><Clock3 size={15}/>{job.start_time.slice(0,5)}–{job.end_time.slice(0,5)}</span>{job.location&&<span><MapPin size={15}/>{job.location}</span>}</div>{job.notes&&<p>{job.notes}</p>}<div className="people">{job.members.map(id=>{const u=data.users.find(x=>x.id===id);return u?<span key={id}>{u.display_name}</span>:null})}</div></div></div>}

function JobModal({job,data,date,me,close,refresh}){const [title,setTitle]=useState(job?.title||''),[start,setStart]=useState(job?.start_time?.slice(0,5)||'13:00'),[end,setEnd]=useState(job?.end_time?.slice(0,5)||'16:00'),[loc,setLoc]=useState(job?.location||''),[notes,setNotes]=useState(job?.notes||''),[members,setMembers]=useState(job?.members||[]),[err,setErr]=useState(''),[busy,setBusy]=useState(false);
 async function save(){setErr('');if(!title.trim())return setErr('กรอกชื่องาน');if(timeToMin(start)>=timeToMin(end))return setErr('เวลางานไม่ถูกต้อง');if(members.length===0)return setErr('เลือกสมาชิกอย่างน้อย 1 คน');setBusy(true);try{const payload={title:title.trim(),date,start_time:start,end_time:end,location:loc.trim()||null,notes:notes.trim()||null};const collisions=data.avail.filter(a=>members.includes(a.user_id)&&a.date===date&&overlap(payload,a));if(collisions.length)return setErr('มีสมาชิกที่ลงเวลาว่างชนกับงานนี้: '+[...new Set(collisions.map(a=>data.users.find(u=>u.id===a.user_id)?.display_name).filter(Boolean))].join(', '));let jobId=job?.id;if(job){const r=await supabase.from('jobs').update(payload).eq('id',job.id);if(r.error)throw r.error}else{const r=await supabase.from('jobs').insert({...payload,created_by:me.id}).select('id').single();if(r.error)throw r.error;jobId=r.data.id}const del=await supabase.from('job_members').delete().eq('job_id',jobId);if(del.error)throw del.error;const ins=await supabase.from('job_members').insert(members.map(user_id=>({job_id:jobId,user_id})));if(ins.error)throw ins.error;close();await refresh()}catch(e){setErr(e.message||'บันทึกงานไม่สำเร็จ')}finally{setBusy(false)}}
 async function remove(){if(!confirm('ลบงานนี้ใช่ไหม?'))return;setBusy(true);const {error}=await supabase.from('jobs').delete().eq('id',job.id);if(error)setErr(error.message);else{close();await refresh()}setBusy(false)}
 return <Modal title={job?'แก้ไขงาน':'สร้างงาน'} close={close}><label>ชื่องาน<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="เช่น ถ่ายงานโรงเรียน"/></label><div className="form-row"><label>เริ่ม<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>ถึง<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label>สถานที่<input value={loc} onChange={e=>setLoc(e.target.value)} placeholder="เช่น โรงเรียน"/></label><label>รายละเอียด<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="รายละเอียดเพิ่มเติม"/></label><label>มอบหมายให้</label><div className="checklist">{data.users.map(u=><label key={u.id} className="check"><input type="checkbox" checked={members.includes(u.id)} onChange={e=>setMembers(v=>e.target.checked?[...v,u.id]:v.filter(x=>x!==u.id))}/>{u.display_name}</label>)}</div>{err&&<div className="error">⚠️ {err}</div>}<button className="primary wide" onClick={save} disabled={busy}>{busy?'กำลังบันทึก...':job?'บันทึกการแก้ไข':'สร้างงาน'}</button>{job&&<button className="danger wide" onClick={remove} disabled={busy}>ลบงาน</button>}</Modal>}

function Admin({data,refresh,me}){const [q,setQ]=useState(''),[err,setErr]=useState('');async function toggle(u){setErr('');if(u.id===me.id&&u.role==='admin'&&data.users.filter(x=>x.role==='admin').length===1)return setErr('ต้องมี Admin อย่างน้อย 1 คน');const next=u.role==='admin'?'member':'admin';const {error}=await supabase.from('profiles').update({role:next}).eq('id',u.id);if(error)setErr(error.message);else await refresh()}const users=data.users.filter(u=>u.display_name.toLowerCase().includes(q.toLowerCase()));return <section><div className="section-top"><div><h2>⚙️ จัดการตุ้ย</h2><p>จัดการสมาชิกและสิทธิ์ของทีม</p></div><div className="search"><Search size={17}/><input placeholder="ค้นหาสมาชิก" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{err&&<div className="error">⚠️ {err}</div>}<div className="admin-stats"><div><b>{data.users.length}</b><span>สมาชิก</span></div><div><b>{data.users.filter(u=>u.role==='admin').length}</b><span>Admin</span></div><div><b>{data.jobs.length}</b><span>งานทั้งหมด</span></div></div><div className="admin-list">{users.map(u=><div className="admin-user" key={u.id}><div className="member-head"><div className="avatar">{u.display_name[0]}</div><div><b>{u.display_name}</b><small>{u.email}</small></div></div><button className="role" onClick={()=>toggle(u)}>{u.role==='admin'?<><Shield size={16}/>Admin</>:<><UserPlus size={16}/>Member</>}</button></div>)}</div><div className="security"><Shield/><div><b>สิทธิ์การใช้งาน</b><p>การตรวจสิทธิ์ Admin ถูกบังคับด้วย Supabase RLS และฐานข้อมูล ไม่ได้พึ่งการซ่อนปุ่มในหน้าเว็บอย่างเดียว</p></div></div></section>}
function Modal({title,close,children}){return <div className="modal-bg" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><h2>{title}</h2><button onClick={close}><X/></button></div>{children}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
